---
# tasks file for desktop
- name: Install Desktop base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ base_packages }}"

- name: Set up vscode
  ansible.builtin.include_tasks:
    file: vscode.yml

- name: Set up nvim
  ansible.builtin.include_tasks:
    file: nvim.yml

- name: Set up x & window manager
  ansible.builtin.include_tasks:
    file: x11.yml

- name: Set up shell
  ansible.builtin.include_tasks:
    file: shell.yml

- name: Set up browsers
  ansible.builtin.include_tasks:
    file: browsers.yml