- name: Add key to microsoft
  ansible.builtin.shell: wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -

- name: Add ms repository
  ansible.builtin.shell: sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

- name: Install vscode from ms repo
  ansible.builtin.apt:
    pkg: code
    state: latest
