---
base_packages:
  - xterm
  - htop
  - iputils-ping
  - inetutils-tools
  - nmap
  - git
  - x11-xserver-utils
  - notion
  - rofi
  - build-essential
  - lua5.4
  - python3-pynvim
  - ripgrep
  - xdotool
  - wget
  - apt-transport-https
  - software-properties-common
  - virtualbox
  - clamav
  - ufw
  - maim
  - openvpn
vscode_extensions:
  - rust-lang.rust-analyzer
username: "nik"
